### ISSUE TITLE
Not all images are jpg

### ISSUE THREAD

**Issue by NHOrus** [ObliviousHarmony/ImgurCrawler#1]
Imgur returns image type in header: Content-Type:"image/png". Even when you request file with incorrect extension.
It should be possible to extract that info and use it when saving data.

**Comment by odeits** [comment]
Should be able to check [WebResponse.ContentType](https://msdn.microsoft.com/en-us/library/system.net.webresponse.contenttype(v=vs.110).aspx) assert that it starts with 'image/' and then take the rest as the extension.

**Comment by odeits** [comment]
Conversely because the image is being parsed (which i don't agree) you can check [Image.RawFormat](https://msdn.microsoft.com/en-us/library/system.drawing.image.rawformat(v=vs.110).aspx) to check what the image format is.

**Comment by ObliviousHarmony** [comment]
I used the parsing as opposed to saving the stream itself because I was being lazy, but I'll add support for different file types and just write the stream to a file, as opposed to parsing it.

**Comment by ObliviousHarmony** [comment]
There we go!
