### ISSUE TITLE
Better 'image not found' check

### ISSUE THREAD

**Issue by odeits** [ObliviousHarmony/ImgurCrawler#2]
By checking response.ResponseUri [WebResponse.ResponseUri](https://msdn.microsoft.com/en-us/library/system.net.webresponse.responseuri(v=vs.110).aspx) you can see what url was actually returned. In the case of 'image not found' it is `http://i.imgur.com/removed.png`

**Comment by ObliviousHarmony** [comment]
Nifty. I'll have to see if Imgur responds to HEAD requests as well, in which case I could avoid downloading these images entirely.

**Comment by odeits** [comment]
You can also set [HttpWebRequest.AllowAutoRedirect](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.allowautoredirect(v=vs.110).aspx) to false

**Comment by ObliviousHarmony** [comment]
I went with the latter, and used HEAD requests to avoid downloading those images at all!
