### ISSUE TITLE
Do not throw exception when encountering status code 500.

### ISSUE THREAD

**Issue by NHOrus** [ObliviousHarmony/ImgurCrawler#4]
Imgur is not always stable. Sometimes, when getting valid-ish request, it returns 500
Crawler gets no idea how to deal with that and skips affected URL.

**Comment by ObliviousHarmony** [comment]
I hadn't really thought of the fact that Imgur sends error messages when it's under load. We should do a thread wait and then resubmit the download again. Just doing Thread.Sleep(1000) and calling the function again recursively should work.

**Comment by ObliviousHarmony** [comment]
Resolved by 2f640760bbd58276e880ca54269ec370be022bd3
